
---
title:     青萍
description: 生活就是一本书，一壶茶，一个阳光明媚的下午！
locale: zh
email: "rmzfle@outlook.com"
url: ""
social:
  github: "erlzhang"
  twitter: "icily0719"
  codepen: "erlzhang"

# Theme Settings
logo: /img/book.svg
rss: "/feed.xml"
theme: 'jekyll-theme-persephone'
theme_setting:
  blog_page: "blog/index.md"
  about_page: "about.md"
  archive_page: "archive.md"
  nav_pages:
    - "about.md"
    - "archive.md"
  lang:
    category_all: "全部"
    blog_title: "博客"
# Jekyll Settings
markdown: kramdown
permalink: /blog/:title:output_ext
timezone: Asia/Shanghai
excerpt_separator: <!--more-->
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      keywords: 叶夕青兮, 原创独立博客, Erl, Jekyll, minimal lifestyle blog
      description: 叶夕青兮，目前还是程序员。这里是她的独立博客，分享编程、建站、生活感悟、旅游随感、读书随笔、原创小说等。
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      toc: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-books
  - jekyll-toc
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - scripts/
